version: '3.7'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
    volumes:
      - '~/azurite:/data'    

  voteapi:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "7240:7240"
      - "5135:5135"
    volumes:
      - ../:/workspace:cached  
    command: /bin/sh -c "while sleep 1000; do :; done"  
